---
path: ''
db:
  adapter: postgres
  database: faculty
  search_path: people,rbac
web_library:
  root: https://uk-ac-york-its-faculty-dev-web-library.s3.amazonaws.com
  version: "4.20.0"
bootstrap_major_version: 5
