version: '2.4'

services:
  builder:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-dev:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
  app:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-postgres:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
    environment:
      BANNER_TEXT: 'This is a Dockerized development instance.'
      BANNER_TYPE: info
      BANNER_DISMISSABLE: 'true'
      DB_HOST: db
      DB_USER: sinatra_base_app
      TZ: Europe/London
    depends_on:
      - db
  web:
    build:
      context: docker
      args:
        - WEB_LIBRARY_ROOT
        - WEB_LIBRARY_VERSION
      target: web
    depends_on:
      - app
    ports:
      - "127.0.0.1:80:80"
  test:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-postgres:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
    environment:
      ALLOW_STRING_WEB_LIBRARY_VERSION: 1
      DB_HOST: db-test
      DB_USER: sinatra_base_app
      TZ: Europe/London
    depends_on:
      - db-test
  db:
    image: ghcr.io/university-of-york/faculty-dev-db-test:latest
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  db-test:
    image: ghcr.io/university-of-york/faculty-dev-db-test:latest

volumes:
  bundle:
  db:
