version: '2.4'

services:
  builder:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-dev:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
  app:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-dev:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
    environment:
      BANNER_TEXT: 'This is a Dockerized development instance.'
      BANNER_TYPE: info
      BANNER_DISMISSABLE: 'true'
      TZ: Europe/London
  web:
    build:
      context: docker
      args:
        - WEB_LIBRARY_ROOT
        - WEB_LIBRARY_VERSION
      target: web
    depends_on:
      - app
    ports:
      - "127.0.0.1:80:80"
  test:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-dev:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
    environment:
      ALLOW_STRING_WEB_LIBRARY_VERSION: 1
      TZ: Europe/London

volumes:
  bundle:
  db:
