version: '2.4'

services:
  builder:
    image: ghcr.io/university-of-york/faculty-dev-docker-images/local-dev/aws-lambda-ruby-dev:2.7
    volumes:
      - .:/var/task
      - bundle:/bundle
  app:
    image: 733046350245.dkr.ecr.eu-west-1.amazonaws.com/mcm-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      - webnet
    ports:
      - '5000:5000'
    environment:
      BANNER_TEXT: 'This is a Dockerized development instance.'
      BANNER_TYPE: info
      BANNER_DISMISSABLE: 'true'
      TZ: Europe/London
  web:
    image: 733046350245.dkr.ecr.eu-west-1.amazonaws.com/mcm-web
    build:
      context: docker/web
      dockerfile: Dockerfile
      args:
        - WEB_LIBRARY_ROOT
        - WEB_LIBRARY_VERSION
      target: web
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - webnet
networks:
  webnet: 
    driver: bridge
volumes:
  bundle:
