
name: Test

on:
  push:
    branches-ignore:
      - base

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: university-of-york/faculty-dev-actions/rubocop@v1

  bundler-audit:
    name: Bundler Audit
    runs-on: ubuntu-latest
    steps:
      - uses: university-of-york/faculty-dev-actions/bundler-audit@v1

  rspec:
    name: RSpec tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uoy-research/rdkit-sqlite-demo:main
      options: '--tmpfs /__e/node20:exec,size=200M'
    steps:
      - name: Bootstrap node20 for glibc2.17
        run: 'cp -a /node_al2/* /__e/node20 && /__e/node20/bin/node -v'
      - name: Install
        run: |
            apt-get update -qq && apt-get -y install git curl gcc make zlib1g-dev libedit-dev libedit2 libssl-dev libffi-dev libyaml-dev
            git clone https://github.com/rbenv/ruby-build.git
            PREFIX=/usr/local ./ruby-build/install.sh
            ruby-build 3.2.4 /__t/Ruby/3.2.4/x64 && touch /__t/Ruby/3.2.4/x64.complete
      - uses: university-of-york/faculty-dev-actions/rspec-runner-github-formatter@v1
