name: Test

on:
  push:
    branches-ignore:
      - base

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: university-of-york/faculty-dev-actions/rubocop@v1

  rspec:
    name: RSpec tests
    container: 
      image: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-dev:2.7
      volumes: 
        - ./db:/db
    runs-on: ubuntu-latest
    steps:
      - uses: university-of-york/faculty-dev-actions/rspec-lambda@v1
        env:
          TZ: Europe/London

  bundler-audit:
    name: Bundler Audit
    runs-on: ubuntu-latest
    steps:
      - uses: university-of-york/faculty-dev-actions/bundler-audit@v1
