name: Bundle Update

on:
  schedule:
    - cron: '0 7 * * THU'
  workflow_dispatch:

jobs:
  bundle-update:
    name: Run bundle update
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-dev:3.2
      options: '--tmpfs /__e/node20:exec,size=200M'
    steps:
      - name: Bootstrap node20 for glibc2.17
        run: 'cp -a /node_al2/* /__e/node20 && /__e/node20/bin/node -v'
      - uses: university-of-york/faculty-dev-actions/bundle-update@v1
        with:
          checkout-key: ${{ secrets.BUNDLE_UPDATE_SSH_PRIVATE_KEY }}
          container: "true"
